# 应用服务 WEB 访问端口
server:
  port: 8080
# 应用名称
spring:
 application: namefoodTraceability

# 数据库驱动：
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
# 数据库连接地址
  url: jdbc:mysql://localhost:3306/food_traceability?serverTimezone=Asia/Shanghai
# 数据库用户名&密码：
  username: root
  password: beichendongmu
  #   Druid数据源配置
  initialSize: 5
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat,wall,log4j
  maxPoolPreparedStatementPerConnectionSize: 20
  useGlobalDataSourceStat: true
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
 thymeleaf:
  cache: false
pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 pageSizeZero: false #pageSize=0




